### ISSUE TITLE
Computerplayer does not expand to stone fields before running out of stone

### ISSUE THREAD

**Issue by andreas-eberle** [jsettlers/settlers-remake#218]
In general, the computerplayer does not expand towards stone fields enough. This can lead to a lack of stone that cannot be solved by the computerplayer any more. 

This can be reproduced on:
* mountainlake: The player in the lower left corner of the map fails to expand to the stone field at its start position.
* The new map Settlers Crater (as suggested in PR #217) causes both AI players to completely run out of stone, although their is stll a lot left. The AI would just need to expand there earlier.

**Comment by codingberlin** [comment]
* mountainlake: The behavior you can observe here is by intention. The yellow ai does have enough stones at the beginning and starts to occupy land in direction of other needed resources. While doing that it occupies some other stonefiels. If yellow runs out of stone later, it is not necessary to build a tower near the start position. yellow can just build stonecutters at the other currently occupied stone fields and can build the tower elsewhere where it is needed more.
* regarding the new Settlers Crater there were two issues I fixed now:
-> If the player needs stones, he searched for stones and two other needed resources which was implemented so that the ai builds towers to gain 3 targets. But unfortunately this could lead in not so efficient towers regarding the essential stones -> so I changed this a bit: If trees and/or stones are missing, no other recourse is important, then towers will be build for tress and/or stones only.
-> Second the finding tower position algorithm was not save in that way if no needed resources are left in the default partition, which is the case with fish on the Settlers Crater. Then no tower was build at all. I fixed that in excluding the resources for the tower build position algorithm when there is nothing left.

**Comment by andreas-eberle** [comment]
First of all, thanks for your improvements.

I figured out one more situation, with an AI player running out of stone. However, this is not because there is not enough stone in the player's occupied area but because the AI destroys all its stone cutters.

With the version of PR #220, the blue player destroys his stonecutters at about 2:10 to 2:25 hours. I guess this is due to the fact that the yellow player divides the blue player's homeland from his occupied space (formerly owned by the green player). In the now divided land, there is plenty of stones lying on the ground (from destroyed buildings).

Maybe the following ideas can help:
* An AI should never run out of stonecutters. If the number of stonecutters gets low (even if there is a lot of stone lying around), new stonecutters must be build immediately. Otherwise it might happend that the AI runs out of stone.
* Maybe there is an issue that the overall stone/material count of all partitions of a player is used, instead of the stone count of the partition managed by the AI. This could explain why now stonecutters are build in the main parititon of the blue player, although there is no stone left at about 2:35h. 
* I guess the AI destroys the stonecutters because they don't find stones in there work area any more. Maybe the AI could also change the work area center for such buildings instead of always building new ones (but this is of course work for an own ticket).

**Comment by codingberlin** [comment]
I changed the destroy stonecutter algorithm. Now it works like that:
- Every AI tick the stonecutters will be checked if they can't work due to missing stones
- The first not working stonecutter (the 5th with WinnerEconomyMinister, and the 3rd with LooserEconomyMinister) will be crushed to be rebuild somewhere else, because the AI has enough other stonecutters to ensure the new stonecutter can be build.
- All other stonecutters get a new work area radius when there is some stone left within the double  of the work area radius of stonecutters distance. If there is no stone, they are destroyed, too.
- The last standing stonecutter won't be destroyed at all. Here the AI waits until another working stonecutter is build or a new tower was build or an enemy tower was occupied. This last stonecutter tries to find stones within the maximum distance of stonecutters work area.

**Comment by codingberlin** [comment]
While working at the stonecutters I optimized the check for blocking work areas of farms and winegrowers.
