### ISSUE TITLE
Can't build mines on steep hills

### ISSUE THREAD

**Issue by abledbody** [jsettlers/settlers-remake#253]
Title says it all. Even if the markers are green, you can't place it.

**Comment by michaelzangl** [comment]
Can you select geologists/other people that are standing there using a single click?

**Comment by abledbody** [comment]
@michaelzangl Yes, definitely. It's not high terrain, like in #215 . It's steep terrain, probably the maximum amount of height difference.

**Comment by michaelzangl** [comment]
@andreas-eberle graphics should send the right position.

**Comment by andreas-eberle** [comment]
@abledbody: Can you tell us a secific map and location on that map where you experienced this issue?

**Comment by abledbody** [comment]
I'm working on a map called overload, if you expand to the east you'll find some mountains which make building mines difficult. [Get it here.](http://download1080.mediafire.com/q6vtv4soi8yg/z1yy9ycf1vdzgq2/overload.map)

**Comment by codingberlin** [comment]
Was able to reproduce it:
When you place an iron mine here:
<img width="1280" alt="bildschirmfoto 2016-05-06 um 22 32 15" src="https://cloud.githubusercontent.com/assets/6422616/15085452/a707b0b6-13da-11e6-92b6-584f72be6f35.png">

Then the ´´´flagsGrids.isProtected(x, y) == true´´´ so that the mine is not build. Here:
https://github.com/jsettlers/settlers-remake/blob/master/jsettlers.logic/src/main/java/jsettlers/logic/map/grid/MainGrid.java#L973

Here is the save game:
[spezialsumpf12-2016-05-06_22-32-34.zmap.gz](https://github.com/jsettlers/settlers-remake/files/252998/spezialsumpf12-2016-05-06_22-32-34.zmap.gz)

**Comment by andreas-eberle** [comment]
@codingberlin: Thanks for the debugging and detailed information. I'll have a look.

**Comment by abledbody** [comment]
Presumably fixed by #428.
