### ISSUE TITLE
Do not print the same message multiple times.

### ISSUE THREAD

**Issue by DerKrawallkeks** [jsettlers/settlers-remake#280]
Hey:)
I don't think it's necessary to have a notification for each hit that a soldier takes. Doesn't sound good and spams the notification section. By the way..please make notifications disappear after a few seconds if possible:)

**Comment by Zervox** [comment]
it does the same on PC, besides this is under development, it's the same thing with woodworker can't find work etc it gets spammed, I think this is done atm for debugging.

**Comment by DerKrawallkeks** [comment]
Okay, thanks

**Comment by JKatzwinkel** [comment]
Avoiding rapidly repeated messages from buildings is not a problem because buildings don't move. But attack messages don't come from stationary positions, and this necessitates heuristics for determining whether an incoming message reports a known incident or a different attack. I feel like I achieved satisfactory results by ignoring all attack messages that originate from within a [*arbitrarily chosen*] range of 50 tiles around where the latest reported attack took place.

Removing messages older than 60 seconds makes sure that even redundant attack messages are shown at least once a minute, in case someone manages to miss it the first time.

**Comment by andreas-eberle** [comment]
Fixed with #331.
