### ISSUE TITLE
Android: Unable to make special settlers

### ISSUE THREAD

**Issue by stumpdk** [jsettlers/settlers-remake#30]
When selecting settlers on Android, the menu for creating special settlers such as geologists is no displayed. JSettlers v. 0.1.1. Build b66ae74.

**Comment by michaelzangl** [comment]
There is no such menu ;-)

**Comment by stumpdk** [comment]
Okay. How are you supposed to create geologists then? :)

**Comment by DerKrawallkeks** [comment]
Same "problem". Well, not a problem, but yea. We need more menus on android. The game is hardly playable, after you've done the basic infrastructure, because of missing advanced menus. I'd be even happy if the original "HUD" would be included in the android version, even though it's a bit small then. But better than nothing;)
I think Android will be the most important platform in the end!..

**Comment by derfuhrer2007** [comment]
Was this fixed?

**Comment by andreas-eberle** [comment]
It's not yet in the master. But @michaelzangl is working on it. It will probably be in the next release.

**Comment by Sylapse** [comment]
This is implemented now on the Android updates I've been working on.

![screenshot_20170113-152246](https://cloud.githubusercontent.com/assets/10612949/21938115/33a3c8d4-d9ba-11e6-98ab-850cc34e9569.png)


![screenshot_20170113-175722](https://cloud.githubusercontent.com/assets/10612949/21938118/35caa65a-d9ba-11e6-90a0-b762948af251.jpg)

**Comment by Tom-Pratt** [comment]
resolvable
