### ISSUE TITLE
way finding algorithm results in jams

### ISSUE THREAD

**Issue by homoroselaps** [jsettlers/settlers-remake#309]
As the way finding mechanism chooses always the shortest route, this results in jams. The settles never choose a different one, even if they have to wait a long long time.
Builders in the way are a common problem, which causes the building process to slow down drastically.
![commonbuilderjam](https://cloud.githubusercontent.com/assets/7871498/13557335/d740aa42-e3ee-11e5-8bc5-5c9b5f57fa00.png)

**Comment by homoroselaps** [comment]
My proposal: if a settler cannot walk to the next path for a long time, have a look for free patches next to it, choose one by random and calculate a new path.

**Comment by andreas-eberle** [comment]
Yes, I know that problem very well... It can be divided into two problems: 

1. The situation with the builders should be locally fixable and normally, settlers should already walk around single other settlers standing in there way. I will have a look at that again.
 
2. The general issue with jams caused by many people using the same shortest path cannot be fixed that easily (at least I didn't find a solution with an acceptable performance). The key issue is that the A* algorithm often finds the same shortest paths for many settlers; although they might have differing start and target locations. This can for example be observed when sending a bunch of soldiers somewhere. I'm open for discussion and PullRequests regarding this problem ;)

**Comment by andreas-eberle** [comment]
I was able to fix part 1 in #312.

**Comment by andreas-eberle** [comment]
@homoroselaps: Why did you close this issue?

**Comment by homoroselaps** [comment]
Because you fixed a part of it and there is already an issue out there which targets the main problem.
