### ISSUE TITLE
Change short to int

### ISSUE THREAD

**Issue by homoroselaps** [jsettlers/settlers-remake#318]
lets change all occurrences of short to int - for better consistency and "better" performance
[https://stackoverflow.com/questions/14531235/in-java-is-it-more-efficient-to-use-byte-or-short-instead-of-int-and-float-inst](url)

**Comment by michaelzangl** [comment]
Most places using shorts are using them to actually save memory. Graphics uses 16 bit colors (5551) to store images.

But I agree to change more short to int as long as the values are used on the stack. ShortPoint2D has historic reasons as well - we do not save anything by keeping it a short value.

But please consider if that value even needs to be a number. Players are better represented by a "Player" object. If we ever want to implement teams or player colors, this will make implementation a lot easier. So instead of convertig all bytes to ints, we should convert them to Player objects.

For space efficiency, we should instead pack points to int values. I did this in the computerplayer code to reduce the memory footprint significantly. But only do this if you really feel the need for it and did a lot of profiling on it ;-).

**Comment by andreas-eberle** [comment]
Using short instead of int has not only history reasons, in fields and arrays this helps to keep the memory footprint down to a value that can run on Android devices. 

The broad usage of shorts in the remaining code and method arguments is to ensure type safety. If a method can only take a short value, where a short value is saved later on, I don't have to check the bounds of the incomming integer. 

But yes, there are some usages (in calculations) where we maybe shouldn't use shorts, as this causes the penalties described in the post you linked. However, in general, I would really try to not use any bit magic to pack shorts into ints...

**Comment by andreas-eberle** [comment]
@homoroselaps: Why did you close this issue?
