### ISSUE TITLE
AI should use geologists

### ISSUE THREAD

**Issue by derfuhrer2007** [jsettlers/settlers-remake#393]
From the looks of it, AI already knows where to place the mines, without any aid from geologists.

For realism's sake, they should go through the same process as us.

**Comment by andreas-eberle** [comment]
The current AI is an all-knowing AI. And for the sake of making it hard to win against it, this will not change in the (near to far) future. That's simply because it's much harder to play with only the limitted knowledge of a normal player. 

However, I agree that the AI should create some geologists and have them work to at least look like it's using them...

@codingberlin: What do you think?

**Comment by codingberlin** [comment]
I agree: It looks nicer when the AI sends out some geologists.

**Comment by codingberlin** [comment]
(closing the issue was by accident)
