### ISSUE TITLE
cannot_find_work_WINEGROWER

### ISSUE THREAD

**Issue by derfuhrer2007** [jsettlers/settlers-remake#395]
Was getting this error after I placed 3 wineyards and they were not working.

After I moved their work area in between the rocks they all started working but the error is still popping.`
![screenshot 6](https://cloud.githubusercontent.com/assets/18621498/14938416/3a79c054-0f40-11e6-8fdb-31bdb96481bc.png)

**Comment by andreas-eberle** [comment]
Well, there is two things. 
* we need to localize the message
* the message is shown whenever a winegrower does not have enough space to start or continue its work. It was shown at the beginning, as they most likely had no hilly terrain in their work area (vines can only be grown in a slope. After you changed the work area, they can grow some vines, but not enough to work all the time. That's why you see the message. I think that's a good behavior, as it helpes you to optimize your economy. @codingberlin: You as an experienced player, what do you think about this point?

**Comment by derfuhrer2007** [comment]
Maybe something like this should be implemented in all farm buildings maybe with some notice above the building, so that you know you are encroaching it's territory

**Comment by andreas-eberle** [comment]
This is implemented in all farm buildings.

**Comment by codingberlin** [comment]
On the one hand I agree that the winegrowers' localization in the picture is not optimal and the player should be informed about that
On the other hand I think spamming the player with "can not work" messages might be a bit annoying.

What about sending the message once the winegrower can not work until the player changes the work area. If again the new work area is not 100% optimal we send the message again (once).

**Comment by derfuhrer2007** [comment]
Or add some vertical meter next to it, showing it's efficiency. Something of a passive information, as this shouldn't be that critical as a notification.

**Comment by andreas-eberle** [comment]
I think displaying the productivity like we do it for mines is a good idea. I opened #402 for this task. As the localization has been fixed and the rest will be handled in the new issue, I will close this one.
