### ISSUE TITLE
Some weapon smiths not working

### ISSUE THREAD

**Issue by derfuhrer2007** [jsettlers/settlers-remake#448]
The top three ones are not in use, though no such order was given
![screenshot 11](https://cloud.githubusercontent.com/assets/18621498/15448538/179a2cd4-1f82-11e6-88d6-01ab2cbfd22d.png)
[2016-05-20_23-48-08_Nice_Map (3).zip](https://github.com/jsettlers/settlers-remake/files/275865/2016-05-20_23-48-08_Nice_Map.3.zip)

**Comment by codingberlin** [comment]
If I see it correctly on the screenshot the weapon smiths which do not produce have a full stack of 8 spears. If the stacks are full they can't produce anymore.

Nevertheless because of your this issue I checked the AI and found out that in the case that the minimum amount of swordsmen or pikemen is not reached the AI add some priority production for the missing weapons and disabled the normal production. And when the smiths have finished the priority production they stop working until the next AI game tick recognizes it and enables normal production again.

I fixed this bug within the #427 pull request. Now the AI configures additional normal weapons production parallel to the priority production in the above cases.

**Comment by derfuhrer2007** [comment]
I see.

I never gave it the order to produce pikes, just swords and bows a couple of times.

**Comment by andreas-eberle** [comment]
Is this a screenshot where you played yourself, or did you let the AI play? Please attach the replay file, so I can replay the game and check the causes.

**Comment by derfuhrer2007** [comment]
The replay file should be in the first post.

Yep, those are my weapon smiths
