### ISSUE TITLE
Wood cutters produced log count doesnt increase while selected

### ISSUE THREAD

**Issue by tom-pratt** [jsettlers/settlers-remake#534]
As long as the building selection content is open for the wood cutter, it's number of outputted logs doesnt increment. If you select something else then reselect the woodcutter is reflects the true count.

The same thing happened while working on Android version so probably not just a graphical code bug. Think the wrong data is coming through in the StackStates.

<img width="174" alt="capture" src="https://cloud.githubusercontent.com/assets/10612949/21929916/95ef8612-d993-11e6-85bd-653d932b9213.PNG">

**Comment by andreas-eberle** [comment]
Did you request the current state from the game logic? The object you get from such a request is (afaik) constant and hence will not be updated. To get the current state you need to request the current state regularly.

**Comment by Sylapse** [comment]
Yeah checking using the BuildingState's isStillInState() method in every draw event and then getting a new BuildingState if true. I think because the problem exists in Android and Desktop versions there must be a bug in the game logic. isStillInState() often returns false causing a UI update but the StackStates inside the new BuildingState still contain old information.

The only pattern I can see so far is. Is that the StackStates are created with out of date data while a wood cutter is the current selection. I'm not sure what's going on in the underlying Building object at this point as I haven't dug that deep.

**Comment by andreas-eberle** [comment]
@tom-pratt: I think found it. The stack states were correctly checked... but then there was a not missing in the next if... should be fixed in 081eb05.
