### ISSUE TITLE
Movables sometimes get stuck

### ISSUE THREAD

**Issue by namelessjames** [jsettlers/settlers-remake#59]
In this example, carriers sometimes get stuck between a building or build site and a stone resource object after for example delivering a resource for building. Unfortunately, this is very hard to reproduce. As far as i know, this has always been an issue on the original game as well, though there was no other solution as to delete the building or even restart the game (when settlers got stuck on the environment).

The issue can be resolved by converting the movable to a controllable one (like a pioneer) by then move it out of the way in either northern or southern direction. 

Edit: also happens, when movables are staying inside the work area  of a forester. Once the trees have grown, they won't come out.

![untitled-1](https://cloud.githubusercontent.com/assets/858474/7366467/c1795f12-ed98-11e4-9ff5-1033ca39f9de.jpg)

**Comment by andreas-eberle** [comment]
Are you sure that the movables are really stuck? Did you try to get this settler some work? I guess if he gets work, e.g. when you build some buildings, so that all settlers need to carry something, he will move and not be "stuck" any more. 

Unfortunately, I cannot see the stuck settler on your screenshot. Can you append a screenshot where I can see that settler? You could also send me an email with the replay file and the exact game time of the issue. 

Many thanks + best regards

**Comment by namelessjames** [comment]
Hi @andreas-eberle 
acutally, it currently seems as if I was just assuming that those settlers where stuck because they where moving back and forth. This is then not a bug, it is a feature request to improve the movement so that one does not assume that a settler is being stuck :smile:

**Comment by adamjryan** [comment]
#68 addresses this.
