### ISSUE TITLE
Website misconfigured: settlers-android-clone.com

### ISSUE THREAD

**Issue by execthis** [jsettlers/settlers-remake#684]
http://www.settlers-android-clone.com

regards
Remo

**Comment by DerKrawallkeks** [comment]
I agree. Had this issue for at least a week or two. I just didn't realize it wasn't me.

**Comment by andreas-eberle** [comment]
Hi guys,

unfortunately, the website is down on purpose. The problem is that Ubisoft reached out to us and claimed we'd infringe their copyrights and trademarks with our website. I'm still trying to get to work this out with them...

But thanks for reporting and following the project!

(I'll keep this issue open, so others can see it.)

**Comment by andreas-eberle** [comment]
The website is back online again. I removed the problematic stuff.
