### ISSUE TITLE
Settlers pathfinding

### ISSUE THREAD

**Issue by Zervox** [jsettlers/settlers-remake#7]
The Unit AI for builders and/or carrier starts to walk in tight circles if blocked by rocks never getting from and to target locations(leads to unfinished buildings).

**Comment by andreas-eberle** [comment]
Can you attach the replay file and the logfiles of your game (see https://github.com/jsettlers/settlers-remake#found-a-bug-report-it). This will help me a lot to reproduce it.

Thanks in advance.

**Comment by Zervox** [comment]
http://www.mediafire.com/download/kb0d1ec5l0v6eo6/2015-04-06_17-07-40_Nice_Map.rar

I think this is the correct replay file, note the builder in the top left corner by the tower, I can't seem the other replay where diggers and carriers were doing the same thing.

Might I ask what would cause a map to make the behavior of the game break? map size? or is there some special scripts?

Just asking as I've been unable to get the MapEditor to run, it also does not generate any logs, this is on Windows 7 64bit for additional information by the way.

**Comment by andreas-eberle** [comment]
Hi Zervox, 

the bug wasn't caused by the map directly. Instead it was a bug in the implementation of the Settlers, which caused them to be no longer subscribed to the game timer. That caused #6 and this behavior. 

I guess it happend on Nice Map because there were a lot of jobless settlers at start and the bug only happend to jobless settlers.

I fixed the bug an two more and just released a new version.

Best regards + many thanks for reporting!
